### ISSUE TITLE
The google map with the sites is missing from the website

### ISSUE THREAD

**Issue by lulin-song** [hudsonriverlife/riverlife#1]
Needs more detail from Laurel and Margei

**Comment by lzaima** [comment]
<img width="1277" alt="Screen Shot 2019-05-01 at 3 39 39 PM" src="https://user-images.githubusercontent.com/50177383/57038198-6412f880-6c27-11e9-8619-6d521218ee0c.png">

**Comment by lzaima** [comment]
I think this is resolved.
