### ISSUE TITLE
2017 and 2018 Data into the Database 

### ISSUE THREAD

**Issue by columbiaclimatecenter** [hudsonriverlife/riverlife#4]
Hi Lulin, Margie and I really need the 2017 and 2018 data to be uploaded to the database as we are starting to do teacher trainings around it in the next couple weeks. Can you tell us when it will all be in? Thank you, Laurel

**Comment by columbiaclimatecenter** [comment]
Margie and I checked the database online, and we found the entire webpage to be down. Do you know what is happening? Can you please upload the 2017 and 2018 data ASAP?

**Comment by lulin-song** [comment]
* hudson test database created.
* Both 2017 and 2018 data were loaded into hudson test database.
* 15 SQL query files were uploaded into Dropbox.

**Comment by lulin-song** [comment]
The server was rebooted in June 25, 2019. The programs were started up automatically. But the program has database connection issues. This cause the site is not reachable. I believe either changes made on the server or changes made to database caused this issue.

**Comment by lulin-song** [comment]
Loaded into database last year. Close now.
